<a href="https://colab.research.google.com/github/lordBruticus/GIMM-400-Uitilities-Project/blob/master/Utilities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hello World**

In [0]:
Console.WriteLine("Hello world");

string aFriend = "Bill";
Console.WriteLine(aFriend);

//aFriend = "Maria";
//Console.WriteLine(aFriend);
//Console.WriteLine("Hello " + aFriend);
//Console.WriteLine($"Hello  {aFriend}");

//string firstFriend = "Maria";
//string secondFriend = "Sage";
//Console.WriteLine($"My friends are {firstFriend} and {secondFriend}");

//Console.WriteLine($"My friends are {secondFriend} and {firstFriend.Length} letters.");
//Console.WriteLine($"My friends are {firstFriend} and {secondFriend.Length} letters.");

string greeting = "    Hello World    ";
Console.WritieLine($"[{greeting}]");

string trimmedGreeting = greeting.TrimStart();
Console.WriteLine($"[{trimmedGreeting}]");

trimmedGreeting = greeting.TrimEnd();
Console.WriteLine($"[{trimmedGreeting}]");

trimmedGreeting = greeting.Trim();
Console.WriteLine($"[{trimmedGreeting}]");

string sayHello = "Hello World!";
Console.WriteLine(sayHello);
sayHello = sayHello.Replace("Hello", "Greetings");
Console.WriteLine(sayHello);

Console.WriteLine(sayHello.ToUpper());
Console.WriteLine(sayHello.ToLower());

string songLyrics = "You say goodbye, and I say hello";
Console.WriteLine(songLyris.Contains("goodbye"));
Console.WriteLine(songLyris.Contains("greetings"));

string songLyrics = "You say goodbye, and I say hello";
Console.WriteLine(songLyrics.StartsWith("You"));
Console.WriteLine(songLyrics.StartsWith("goodbye"));

Console.WriteLine(songLyrics.EndsWith("hello"));
Console.WriteLine(songLyrics.EndsWith("goodbye"));

**Neural Networks: Simple to Complex**

In [0]:
# Simple Feedforward Artificial Neural Network: no external libraries like tensorflow, pandas, numpy, or keras:
# No backpropogation or optimization:

epoch = 5 #number of times you will run the neural net through the entire training set FIX THIS
lr = .00001 #learning rate FIX THIS
bias = .1 #value of bias FIX THIS
weights = [random.random(),random.random(),random.random()] #weights generated in a list (3 weights in total for 2 neurons and the bias)
print("Weights before training: " + str(weights))

def NeuralNet(weights, inputNeuron1, inputNeuron2, expectedOutput):
  outputActual = inputNeuron1*weights[0]+inputNeuron2*weights[1]+bias*weights[2]
  outputActual = ApplyActivation(outputActual)
  error = expectedOutput - outputActual #simple error measurement
  #inference: here we train the hidden layer which is just an array of weights.
  weights[0] += error * inputNeuron1 * lr
  weights[1] += error * inputNeuron2 * lr
  weights[2] += error * bias * lr
def ApplyActivation(actInput):
  if actInput > 0 : #activation function (here Heaviside because we want a 0 or 1 answer)
     actInput = 1
  else :
     actInput = 0
  return actInput


for i in range(epoch):
  NeuralNet(weights, 1,1,1) #True or true input should return true
  NeuralNet(weights, 1,0,1) #True or false input should return true
  NeuralNet(weights, 0,1,1) #False or true input should return true
  NeuralNet(weights, 0,0,0) #False or false input should return false
  
print("Weights after training: " + str(weights))
x = int(input())
y = int(input())
output = x*weights[0] + y*weights[1] + bias*weights[2]
if output > 0 : #activation function
   output = 1
else :
   output = 0
print(x, "or", y, "is : ", output)



Weights before training: [0.12417331511991114, 0.2791836790111395, 0.5857592714582879]
Weights after training: [0.12417331511991114, 0.2791836790111395, 0.5857542714582877]
0
0
0 or 0 is :  1


In [0]:
import numpy as np #import numpy the linear algebra library

# sigmoid function - introduces non-linearity into the neural net (not 1-1 input output)
#sigmoid maps to a value between 0 and 1 to convert numbers to probabilities
def nonlin(x,deriv=False):
    if(deriv==True): # when true, this maps the derivative of the sigmoid function - so we can get the slope at a given point
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
epochs = 10000
weights = np.array([[0,0,0,0]]).T
# initialize weights randomly with mean 0
#we only have an input and output layer, so we only need on matrix of wieghts to connect them with dimensions (3,1) 3 inputs to 1 output
#if we wanted to change the number of inputs we would also change this (3,1) to reflect inputs, but we generally want 1 output since we're doing a regresion neural net
#syn0 = 2*np.random.random((3,1)) - 1

def neuralNet(l0, epochs, predict, userTest=[0,0,0], testWeights=[0,0,0,0]):
  if(not predict):
    for iter in range(epochs):

      # forward propagation - the prediction step, we let the network try to predict it's output and measure the error
      syn0 = testWeights
      #this is the 'weighted sum step where we use the dot or cross product of two matrices to output a matrix that has the multiplied and summed total of the weights and values for that row and column combination, and then we convert that back into a number since we get a probability with the sigmoid function'
      #the dimensions going on in the next step are: (4X3)dot(3X1) = (4X1) so everything in the matrix gets multplied and hte result is a matix with the number of rows in first matrix and number of columns in second
      l1 = nonlin(np.dot(l0,syn0)) #multiplies 10 input by syn0 weights, then passes it through our sigmoid function to convert the numbers to probabilities 
      

      # compare our guess - l1 - to the actual answer - y -
      l1_error = y - l1
      if(iter % 999 == 0):
        print('error before slope of sigmoid of values in l1')
        print(l1_error)
        print("l1 itself (dot product of l0 and weight (weighted sum))")
        print(l1)
    

      # multiply how much we missed by the 
      # slope of the sigmoid at the values in l1 - basically we multiply elementwise a 4,1 matrix with another 4,1 matrix of its sigmoid derivatives thereby reducing the error of high confidence predictions.
      # if the network has a very confident guess (slope is very shallow or close to 0), we leave it alone with the multiplication here but if it's closer to .5 then we heavily update the guess with this multiplication
      l1_delta = l1_error * nonlin(l1,True)
      if(iter%999 == 0):
        print('error after slope of sigmoid of values in l1 is multiplied times l1 error')
        print(l1_delta)
        
    

     # update weights (again cross multiplication , added to all weights between the two matrix)
      syn0 += np.dot(l0.T,l1_delta)
    return syn0,l1
    
  if predict:           
          
    syn0 = testWeights
    total = 0    #the dimensions goig on in the next step are: (4X3)dot(3X1) = (4X1) so everything in the matrix gets multplied and hte result is a matix with the number of rows in first matrix and number of columns in second
    for i in range(len(userTest)):
      #multiplies 10 input by syn0 weights, then passes it through our sigmoid function to convert the numbers to probabilities 
    #print("hey" + str(l1))
      total += userTest[i] * testWeights[i]
        # compare our guess - l1 - to the actual answer - y -
        # l1_error = y - l1
        #l1_delta = l1_error * nonlin(l1,True)
        
    

      # update weights (again cross multiplication , added to all weights between the two matrix)
        #syn0 += np.dot(l0.T,l1_delta)
     # return the prediction:
    return nonlin(total)
      
w,l1 = neuralNet(X,1000, False, testWeights = 2*np.random.random((3,1)) - 1)
print("Output After Training:")
print(str(l1))
print("Weights: " + str(w))
#user test:
userInput = input("Enter int array: ")
userArray = list(map(int, userInput.split()))
print(userArray)
print(str(neuralNet(X,1,True, userTest=userArray, testWeights=w)))
#Note that adding a 0 0 0 learning set and a 0 1 0 doesn't work yet, we need to introduce two hyperparameters, layers, numbers of neurons, and an alpha or (learning rate)
#Try 1 1 0 which is not in the data set, but if assume the rule it's trying to infer is perfect correspondence to the first column should return 1

error before slope of sigmoid of values in l1
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
l1 itself (dot product of l0 and weight (weighted sum))
[[0.2689864 ]
 [0.36375058]
 [0.23762817]
 [0.3262757 ]]
error after slope of sigmoid of values in l1 is multiplied times l1 error
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]
error before slope of sigmoid of values in l1
[[-0.03178421]
 [-0.02576499]
 [ 0.02093318]
 [ 0.02585355]]
l1 itself (dot product of l0 and weight (weighted sum))
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]
error after slope of sigmoid of values in l1 is multiplied times l1 error
[[-0.00097813]
 [-0.00064673]
 [ 0.00042903]
 [ 0.00065113]]
Output After Training:
[[0.03178421]
 [0.02576499]
 [0.97906682]
 [0.97414645]]
Weights: [[ 7.26283009]
 [-0.21614618]
 [-3.41703015]]
Enter int array: 0 1 1
[0, 1, 1]
[0.02575143]


In [0]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
  # It's really just 2 of the previous implementation stacked on top of each other. The output of the first layer (l1) is the input to the second layer.
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)? This is a critical step!
    # use the "confidence weighted error" from l2 to establish an error for l1. To do this, send the error across the weights from l2 to l1. 
    # This gives what you could call a "contribution weighted error" because we learn how much each node value in l1 "contributed" to the error in l2. This step is called "backpropagating" and is the namesake of the algorithm. We then update syn0 using the same steps we did in the 2 layer implementation.
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)


Error:0.4964100319027255
Error:0.008584525653247157
Error:0.0057894598625078085
Error:0.004629176776769985
Error:0.0039587652802736475
Error:0.003510122567861678


In [0]:
import numpy as np

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)
    
# input dataset
X = np.array([  [0,1],
                [0,1],
                [1,0],
                [1,0] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
synapse_0 = 2*np.random.random((2,1)) - 1

for iter in range(10000):

    # forward propagation
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0,synapse_0))

    # how much did we miss?
    layer_1_error = layer_1 - y

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)
    synapse_0_derivative = np.dot(layer_0.T,layer_1_delta)

    # update weights
    synapse_0 -= synapse_0_derivative

print("Output After Training:")
print(layer_1)

Output After Training:
[[0.00505119]
 [0.00505119]
 [0.99494905]
 [0.99494905]]


In [0]:
import numpy as np
#Challenge: find the best hyperparameters from alpha and hidden layer sizes
#Bonus extend this to an artibray user enter number of hidden layers with user entered sizes
alphas = [0.001,0.01,0.1,1,10,100,1000]
hiddenSizes = [4,8,16,32]

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

for alpha in alphas:
  for hiddenSize in hiddenSizes:
    print("\nTraining With Alpha:" + str(alpha) + " and hidden layer size: " + str(hiddenSize))
    np.random.seed(1)

    # randomly initialize our weights with mean 0
    synapse_0 = 2*np.random.random((3,hiddenSize)) - 1
    synapse_1 = 2*np.random.random((hiddenSize,1)) - 1

    for j in range(60000):

        # Feed forward through layers 0, 1, and 2
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0,synapse_0))
        layer_2 = sigmoid(np.dot(layer_1,synapse_1))

        # how much did we miss the target value?
        layer_2_error = layer_2 - y

        if (j % 20000) == 0:
            print("Error after "+str(j)+" iterations:" + str(np.mean(np.abs(layer_2_error))))

        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        layer_2_delta = layer_2_error*sigmoid_output_to_derivative(layer_2)

        # how much did each l1 value contribute to the l2 error (according to the weights)?
        layer_1_error = layer_2_delta.dot(synapse_1.T)

        # in what direction is the target l1?
        # were we really sure? if so, don't change too much.
        layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)

        synapse_1 -= alpha * (layer_1.T.dot(layer_2_delta))
        synapse_0 -= alpha * (layer_0.T.dot(layer_1_delta))




Training With Alpha:0.001 and hidden layer size: 4
Error after 0 iterations:0.4964100319027255
Error after 20000 iterations:0.4935960431880486
Error after 40000 iterations:0.48910016654420474

Training With Alpha:0.001 and hidden layer size: 8
Error after 0 iterations:0.49885891282661
Error after 20000 iterations:0.4960339829421634
Error after 40000 iterations:0.49230609024302613

Training With Alpha:0.001 and hidden layer size: 16
Error after 0 iterations:0.4968197940374576
Error after 20000 iterations:0.4915701638369947
Error after 40000 iterations:0.4835511920051555

Training With Alpha:0.001 and hidden layer size: 32
Error after 0 iterations:0.49643992250078794
Error after 20000 iterations:0.48497630702745953
Error after 40000 iterations:0.46903846539028254

Training With Alpha:0.01 and hidden layer size: 4
Error after 0 iterations:0.4964100319027255
Error after 20000 iterations:0.359097202563399
Error after 40000 iterations:0.14307065901337032

Training With Alpha:0.01 and hidden

**Classifying Images**

In [0]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass


In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

In [0]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [0]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [0]:
train_images.shape

In [0]:
len(train_labels)

In [0]:
train_labels

In [0]:
test_images.shape

In [0]:
len(test_labels)

In [0]:
plt.figure()
plt.imshow(train_images[0])
plt.colorbar()
plt.grid(False)
plt.show()

In [0]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [0]:
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[train_labels[i]])
plt.show()

In [0]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(train_images, train_labels, epochs=10)

In [0]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

In [0]:
predictions = model.predict(test_images)

In [0]:
predictions[0]

In [0]:
np.argmax(predictions[0])

In [0]:
test_labels[0]

In [0]:
def plot_image(i, predictions_array, true_label, img):
  predictions_array, true_label, img = predictions_array, true_label[i], img[i]
  plt.grid(False)
  plt.xticks([])
  plt.yticks([])

  plt.imshow(img, cmap=plt.cm.binary)

  predicted_label = np.argmax(predictions_array)
  if predicted_label == true_label:
    color = 'blue'
  else:
    color = 'red'

  plt.xlabel("{} {:2.0f}% ({})".format(class_names[predicted_label],
                                100*np.max(predictions_array),
                                class_names[true_label]),
                                color=color)

def plot_value_array(i, predictions_array, true_label):
  predictions_array, true_label = predictions_array, true_label[i]
  plt.grid(False)
  plt.xticks(range(10))
  plt.yticks([])
  thisplot = plt.bar(range(10), predictions_array, color="#777777")
  plt.ylim([0, 1])
  predicted_label = np.argmax(predictions_array)

  thisplot[predicted_label].set_color('red')
  thisplot[true_label].set_color('blue')

In [0]:
i = 0
plt.figure(figsize=(6,3))
plt.subplot(1,2,1)
plot_image(i, predictions[i], test_labels, test_images)
plt.subplot(1,2,2)
plot_value_array(i, predictions[i],  test_labels)
plt.show()

In [0]:
i = 12
plt.figure(figsize=(6,3))
plt.subplot(1,2,1)
plot_image(i, predictions[i], test_labels, test_images)
plt.subplot(1,2,2)
plot_value_array(i, predictions[i],  test_labels)
plt.show()

In [0]:
# Plot the first X test images, their predicted labels, and the true labels.
# Color correct predictions in blue and incorrect predictions in red.
num_rows = 5
num_cols = 3
num_images = num_rows*num_cols
plt.figure(figsize=(2*2*num_cols, 2*num_rows))
for i in range(num_images):
  plt.subplot(num_rows, 2*num_cols, 2*i+1)
  plot_image(i, predictions[i], test_labels, test_images)
  plt.subplot(num_rows, 2*num_cols, 2*i+2)
  plot_value_array(i, predictions[i], test_labels)
plt.tight_layout()
plt.show()

In [0]:
# Grab an image from the test dataset.
img = test_images[1]

print(img.shape)

In [0]:
# Add the image to a batch where it's the only member.
img = (np.expand_dims(img,0))

print(img.shape)

In [0]:
predictions_single = model.predict(img)

print(predictions_single)

In [0]:
plot_value_array(1, predictions_single[0], test_labels)
_ = plt.xticks(range(10), class_names, rotation=45)

In [0]:
np.argmax(predictions_single[0])

**Classifying Text**

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

In [0]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

In [0]:
from tensorflow import keras

!pip install tensorflow-datasets
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

import numpy as np

print(tf.__version__)

In [0]:
(train_data, test_data), info = tfds.load(
    # Use the version pre-encoded with an ~8k vocabulary.
    'imdb_reviews/subwords8k', 
    # Return the train/test datasets as a tuple.
    split = (tfds.Split.TRAIN, tfds.Split.TEST),
    # Return (example, label) pairs from the dataset (instead of a dictionary).
    as_supervised=True,
    # Also return the `info` structure. 
    with_info=True)

In [0]:
encoder = info.features['text'].encoder

In [0]:
print ('Vocabulary size: {}'.format(encoder.vocab_size))

In [0]:
sample_string = 'Hello TensorFlow.'

encoded_string = encoder.encode(sample_string)
print ('Encoded string is {}'.format(encoded_string))

original_string = encoder.decode(encoded_string)
print ('The original string: "{}"'.format(original_string))

assert original_string == sample_string

In [0]:
for ts in encoded_string:
  print ('{} ----> {}'.format(ts, encoder.decode([ts])))

In [0]:
for train_example, train_label in train_data.take(1):
  print('Encoded text:', train_example[:10].numpy())
  print('Label:', train_label.numpy())

In [0]:
encoder.decode(train_example)

In [0]:
BUFFER_SIZE = 1000

train_batches = (
    train_data
    .shuffle(BUFFER_SIZE)
    .padded_batch(32, train_data.output_shapes))

test_batches = (
    test_data
    .padded_batch(32, train_data.output_shapes))

In [0]:
for example_batch, label_batch in train_batches.take(2):
  print("Batch shape:", example_batch.shape)
  print("label shape:", label_batch.shape)
  

In [0]:
model = keras.Sequential([
  keras.layers.Embedding(encoder.vocab_size, 16),
  keras.layers.GlobalAveragePooling1D(),
  keras.layers.Dense(1, activation='sigmoid')])

model.summary()

In [0]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [0]:
history = model.fit(train_batches,
                    epochs=10,
                    validation_data=test_batches,
                    validation_steps=30)

In [0]:
loss, accuracy = model.evaluate(test_batches)

print("Loss: ", loss)
print("Accuracy: ", accuracy)

In [0]:
history_dict = history.history
history_dict.keys()

In [0]:
import matplotlib.pyplot as plt

acc = history_dict['accuracy']
val_acc = history_dict['val_accuracy']
loss = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

# "bo" is for "blue dot"
plt.plot(epochs, loss, 'bo', label='Training loss')
# b is for "solid blue line"
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

In [0]:
plt.clf()   # clear figure

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')

plt.show()